### PR TITLE
DM-35962: Remove examples/ from all packages

### PR DESCRIPTION
**Pull request by parejkoj**

### CODE REVIEW

**Review by timj — APPROVED** [review]
This being a notebook makes me wonder if the content of the notebook covers items that are missing from the documentation.

**Comment by parejkoj** [comment]
The notebook here doesn't have any narrative structure, so it's not clear what it's supposed to be demonstrating.

This package is missing from the pipeline docs, and doesn't have a correctly-configured `doc/`. It's not even clear the package works, since the single test file does nothing.

**Comment by timj** [comment]
Ok. The lack of tests in the display packages has always been a problem (it seems there should be a set of tests in afw that the display packages could reuse).

**Comment by gpdf** [comment]
We also clearly have issues in the ability of users to treat afw.display as clearly a backend-agnostic base.  I have recently seen examples where people have completely different call sequences to afw.display depending on which back end they are using.

I think we need a sprint on improving the situation, which could include releasing some more solid tutorial code in a CI-able place.  I've been discussing this with @frossie .

**Comment by gpdf** [comment]
(no objections to removing this particular notebook, for now)

**Comment by RobertLuptonTheGood** [comment]
> We also clearly have issues in the ability of users to treat afw.display as clearly a backend-agnostic base. I have recently seen examples where people have completely different call sequences to afw.display depending on which back end they are using.

Can you provide some examples?  Esp. with display_astrotools becoming available, I agree that now'd be a good time to take a look.

					R

**Comment by gpdf** [comment]
[display_astrowidgets](https://github.com/lsst/display_astrowidgets), I think you mean?

**Comment by gpdf** [comment]
I'm mostly thinking of things I've seen in people's personal code, and I'm not trying to embarrass anyone.  It looked to me like the issue was that laying out a multi-image display grid can't be done in a backend-independent way.  I haven't had the time to dig into it - I don't know if it's a weakness in the common API, or a (fixable) difference in how the backends respond to it, or what.

It's also the case that displaying a catalog over an image _from afw.display_ is being done in a way that makes it impossible to take advantage of a lot of the power of Firefly for working with overlays.  We need to come back to that point - we stalled out on that, collectively, when it first came up.

We haven't seriously looked at this whole system since ~2018, so I think it's time for a sprint on this.

**Comment by parejkoj** [comment]
Finally getting back to this: the discussion above was useful, but there were no objections to removing this notebook, so I am going to merge this ticket.

**Pull request merged**
